### ISSUE TITLE
[META] OSRD - UI-core implementation

### ISSUE THREAD

**Issue by Math-R** [OpenRailAssociation/osrd-ui#5]
META issue to track the progress of ui-core implementation (the list of items below will update frequently)

- [x]  Tailwindcss
- [x]  Globals (fonts, colors)
- [x]  Storybook
- [x]  checkbox
- [x]  buttons
- [x]  radio 
- [x] input (text, number, form validation)
- [x] date picker
- [x] time picker
- [x] tolerance input (https://github.com/OpenRailAssociation/osrd-ui/issues/284)
- [x] suggestion input
- [x] select
- [x] text-area

**Comment by celine-sncf** [comment]
- Storybook pour tester (par @thibautsailly ) & démontrer (en system demo) ?

**Comment by celine-sncf** [comment]
@thibautsailly si tu veux plus de tickets pour suivre la validation des différentes livraisons tu peux créer des tickets liés à cette issue
